### ISSUE TITLE
Example of config reload?

### ISSUE THREAD

**Issue by djMax** [github/multibinder#6]
I'm sure it's obvious to most people, but not yet being an haproxy expert, how does one do a zero downtime config reload with multibinder? Same way as with generic haproxy, or SIGUSR1 to multibinder or what?

**Comment by djMax** [comment]
(might be good to just add that simple line to the haproxy readme)

**Comment by theojulienne** [comment]
@djMax great point, that really should have been in the readme! Does https://github.com/github/multibinder/pull/7 clarify things?

**Comment by djMax** [comment]
Definitely!
