### ISSUE TITLE
confd + multibinder + haproxy

### ISSUE THREAD

**Issue by djMax** [github/multibinder#8]
I'm trying to combine these three in a container. I've got a project here:

https://github.com/gas-buddy/docker-haproxy-multibinder-confd

But unfortunately, it seems to fail on starting the haproxy-proxy like so:

```
2017-01-29T21:19:28Z cc366de4d3e2 confd[6]: INFO Backend set to etcd
2017-01-29T21:19:28Z cc366de4d3e2 confd[6]: INFO Starting confd
2017-01-29T21:19:28Z cc366de4d3e2 confd[6]: INFO Backend nodes set to http://etcd0:4001/
2017-01-29T21:19:28Z cc366de4d3e2 confd[6]: INFO Target config /usr/local/etc/haproxy/haproxy.cfg.erb out of sync
Listening for binds on control socket: /var/run/multibinder.sock
Request: {"jsonrpc"=>"2.0", "method"=>"bind", "params"=>[{"address"=>"0.0.0.0", "port"=>8080, "backlog"=>10240}]}
2017-01-29T21:19:38Z cc366de4d3e2 confd[6]: ERROR "Available polling systems :\n      epoll : pref=300,  test result OK\n       poll : pref=200,  test result OK\n     select : pref=150,  test result FAILED\nTotal: 3 (2 usable), will use epoll.\n\nAvailable filters :\n\t[COMP] compression\n\t[TRACE] trace\n\t[SPOE] spoe\nUsing epoll() as the polling mechanism.\n[ALERT] 028/211928 (21) : sendmsg logger #1 failed: Connection refused (errno=111)\n[ALERT] 028/211928 (21) : sendmsg logger #2 failed: Connection refused (errno=111)\n[ALERT] 028/211928 (21) : sendmsg logger #1 failed: Connection refused (errno=111)\n[ALERT] 028/211928 (21) : sendmsg logger #2 failed: Connection refused (errno=111)\n/usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:59:in `waitpid': No child process (Errno::ECHILD)\n\tfrom /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:59:in `block in <top (required)>'\n\tfrom /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:58:in `loop'\n\tfrom /usr/lib/ruby/gems/2.3.0/gems/multibinder-0.0.4/bin/multibinder-haproxy-wrapper:58:in `<top (required)>'\n\tfrom /usr/bin/multibinder-haproxy-wrapper:22:in `load'\n\tfrom /usr/bin/multibinder-haproxy-wrapper:22:in `<main>'\n"
2017-01-29T21:19:38Z cc366de4d3e2 confd[6]: ERROR exit status 1
```

**Comment by theojulienne** [comment]
It looks like an issue calling `waitpid`, which probably means the haproxy process exited unexpectedly. The last message from haproxy seems to be `sendmsg logger #2 failed: Connection refused`, is it possible the `log` configuration isn't correct? It may also be another error actually causing the exit, but it may not be visible if the logging isn't working.

**Comment by djMax** [comment]
I can confirm that when I modify the multibinder-generated config to replace the fd bind with an ip bind, haproxy stays up. Another detail - this is on alpine in docker... Should that work?

**Comment by djMax** [comment]
any thoughts on this? Not sure what else to debug.

**Comment by theojulienne** [comment]
@djMax I took a closer look today, and noticed a few of things:
 * the multibinder wrapper expects that haproxy doesn't daemonise, so you'll need to [remove this line](https://github.com/gas-buddy/docker-haproxy-multibinder-confd/blob/master/confd/templates/haproxy.tmpl#L2).
 * Running `/sbin/syslogd -O /dev/stdout` during `entrypoint.sh` as well using `/dev/log` as the [log target](https://github.com/gas-buddy/docker-haproxy-multibinder-confd/blob/master/confd/templates/haproxy.tmpl#L3) should hopefully get syslog messages through to Docker logs
 * You'll want to run the `/usr/bin/multibinder-haproxy-wrapper` command just once for the whole instance (you can run it in the background), and then rather than call it again on reload, instead run `kill -USR2 <wrapper pid>` on the process, which will cause it to regenerate the final config dynamically (it's fine if the ERB has changed in the meantime) and cycle haproxy itself.

I'm not sure why you didn't observe the same failure when you removed the fd bind - if you still ran that through the multibinder wrapper I would have expected the same exit condition.

Let me know if this helps! 😄

**Comment by djMax** [comment]
Thanks very much for this! I'm getting closer now. it's running and binding and seemingly reading the right config. Couldn't get stdout logging working, but that's not multibinder related. Two questions:

1) If it's not in daemon mode, that means no nbproc. What's the intent here? All haproxy containers run a single process?
2) kill -USR2 <wrapper pid> seems to just kill the thing. Here's my ps output:

```
PID   USER     TIME   COMMAND
    1 root       0:00 {entrypoint.sh} /bin/sh ./entrypoint.sh
    6 root       0:00 /sbin/syslogd -O /dev/stdout
    7 root       0:00 {multibinder} /usr/bin/ruby /usr/bin/multibinder /var/run/multibinder.sock
    8 root       0:00 confd -onetime -node http://etcd0:4001/
   22 root       0:00 {multibinder-hap} /usr/bin/ruby /usr/bin/multibinder-haproxy-wrapper haproxy -f /usr/local/etc/haproxy/haproxy.cf
   25 haproxy-   0:00 haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -V
```

I do `kill -USR2 22` and then it's just gone:

```
    1 root       0:00 {entrypoint.sh} /bin/sh ./entrypoint.sh
    6 root       0:00 /sbin/syslogd -O /dev/stdout
    7 root       0:00 {multibinder} /usr/bin/ruby /usr/bin/multibinder /var/run/multibinder.sock
    8 root       0:00 confd -onetime -node http://etcd0:4001/
   25 haproxy-   0:00 haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -V
```

**Comment by theojulienne** [comment]
> If it's not in daemon mode, that means no nbproc. What's the intent here? All haproxy containers run a single process?

You're totally right! You can leave in `daemon` and then use `-Ds` as [used in the example in this repo](https://github.com/github/multibinder/blob/master/haproxy/haproxy-multi%40.service#L13), which runs haproxy in systemd-compatible mode which essentially just means the parent pid stays around and waits for the child processes to exit.

> kill -USR2 seems to just kill the thing. Here's my ps output:

This is slightly poorly documented, but the example `multibinder-haproxy-wrapper` tries to read the pid file specified on the [command line for haproxy](https://github.com/github/multibinder/blob/master/bin/multibinder-haproxy-wrapper#L11), so you'll need to add `-p /path/to/a/pid/file` similar to the [example for systemd](https://github.com/github/multibinder/blob/master/haproxy/haproxy-multi%40.service#L13).

**Comment by djMax** [comment]
Isn't that what I have here:

https://github.com/gas-buddy/docker-haproxy-multibinder-confd/blob/master/run-or-reload.sh

```#!/bin/sh

PID=/var/run/multibinder.pid

if [ -z "$PID" ]; then
  kill -USR2 $PID
else
  /usr/bin/multibinder-haproxy-wrapper haproxy -f /usr/local/etc/haproxy/haproxy.cfg.erb -p /var/run/haproxy.pid -V &
  cat $! > $PID
fi```

**Comment by theojulienne** [comment]
@djMax for the pid file, yep - sorry, I must have been looking at an old version of the repo. Was there any output generated after you sent a `USR2` that might indicate why it exited?

**Comment by djMax** [comment]
No, but I'm trying to see if it's getting eaten somewhere because I would assume something would complain.

**Comment by djMax** [comment]
Turns out the -Ds is necessary, because otherwise haproxy won't write the pid. What's confusing us now is that confd doesn't appear to think that the reload script has completed on the first go around. This seems to never return, even though I can't see how, because the PID is written:

```
#!/bin/sh

PID=/var/run/multibinder.pid

echo "[haproxy-confd] run-or-reload called"

if [ -f "$PID" ]; then
  echo "[haproxy-confd] sending USR2 to multibinder"
  kill -USR2 `cat $PID`
else
  echo "[haproxy-confd] running haproxy wrapper"
  nohup /usr/bin/multibinder-haproxy-wrapper haproxy -Ds -f /usr/local/etc/haproxy/haproxy.cfg.erb -p /var/run/haproxy.pid -V &
  echo $! > $PID
fi
```

**Comment by theojulienne** [comment]
I was about to write a guess but then noticed that https://github.com/gas-buddy/docker-haproxy-multibinder-confd/commit/8636526e199cc69949c9c16b87f35a6b735a51a1 was doing exactly what I was about to suggest, did that fix it? 😀

**Comment by djMax** [comment]
Yes, it did indeed seem to fix it. I'm going to try and clean it up a bit then we'll ship it! Other than throwing a boat ton of volume at it, any way to validate the approach not dropping connections? Like some well placed sleeps or something?

**Comment by theojulienne** [comment]
> Like some well placed sleeps or something?

It can, but the sleeps would probably need to be in haproxy. The issue that causes drops without multibinder is detailed in [this engineering blog post](https://githubengineering.com/glb-part-2-haproxy-zero-downtime-zero-delay-reloads-with-multibinder/#haproxy-almost-safe-reloads), so in theory you could add a `sleep(10);` between the final `accept` and `close` in haproxy itself.

The way multibinder itself was tested is to actually completely stop the listening service (such as `haproxy`) and validate that a new connection can still be created and queued, then start the service and observe that it's `accept`ed and completes (because the queue is shared, unlike with separate binds).
