### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by tkald** [github/multibinder#9]
Is multibinder considered to be production ready?

**Comment by theojulienne** [comment]
@tkald We do use it [in production at GitHub](https://githubengineering.com/glb-part-2-haproxy-zero-downtime-zero-delay-reloads-with-multibinder/) - do you have any specific questions around using it in production that would help?

**Comment by tkald** [comment]
@theojulienne 
Thats all I needed to hear :)

**Comment by theojulienne** [comment]
:+1: If you have any other questions, feel free to ping or open a new issue 😀
